### ISSUE TITLE
google assistant event handler progress

### ISSUE THREAD

**Issue by hasauino** [UAEU-IRI/std_googleAssistant#1]
Just wanted to check progress. Let's keep this issue for progress check.

@ReemAlsaffar, I think you can start by doing idea 3 and idea 4 shown [here](https://github.com/UAEU-IRI/std_googleAssistant/wiki/Ideas).

Make a table, where you fill a behaviour, and its corresponding character to send, and a description. 
This table will be used by @Hamda-alnuaimi and @amnaAlnaimi to implement on Arduino.

**Comment by ReemAlsaffar** [comment]
Ok, by the end of the day I will finish the actions.json, hotword.py, and make the table and update it on GitHub @hasauino  Umari<mailto:h.umari@uaeu.ac.ae>
________________________________

**Comment by hasauino** [comment]
If you have a question feel free to ask. Especially about using Pyserial. For the table, each time fill the behaviour you need. For example, you now need the "wake up" behaviour when the conversation is started, so you would create a row in the table like so:

| Behaviour        | Character           | Description  |
| ------------- |:-------------:| -----:|
| wake-up      | '1' | fully extend hand and shake wrist   |

This is just an example.

I suggest you place the table in the README file

**Comment by ReemAlsaffar** [comment]
We will be using the letters for all the behaviours right?
________________________________

**Comment by hasauino** [comment]
Yes

**Comment by ReemAlsaffar** [comment]
I have a question about the games with the buttons for example the person say I want to play a game and the arm will say Rock Paper Scissors or remembering sequence to choose so when the person choose each game will have a letter to send also right? Like for example rock paper scissor letter p and the sequence letter s? And how the buttons will work and be controlled?


________________________________

**Comment by hasauino** [comment]
I think it can be done this way:
when you send for instance ``` 'p' ``` (rock paper scissor game is chosen). The Arduino will start the game, raspberry pi job is done here. The fullfilment response might be something like this:  
_"Click one of the buttons"_

The Arduino will command the hand to make a random shape (rock paper scissor), meanwhile the user also clicks a button. If result is user won, the LEDs light green (RGB LED might be used), if loose, then LEDs lights RED.
Also, if the user looses, the arm can be commanded to show victory sign.

So from your end, you just send a character and that's it.
```Python
# placed in the event handler
if (condition to check for action == 'rock_paper_scissor_game'):
     ser.write('p')
```

**Comment by ReemAlsaffar** [comment]
<img width="729" alt="error" src="https://user-images.githubusercontent.com/45401887/50826021-0bf07780-1354-11e9-8c62-1a2c3ba96dd5.PNG">
I got this error while updating the actions.json, and I could not know where the problem is?
I checked the file with json viewer and there was no error

**Comment by hasauino** [comment]
There is something wrong with the action.json file. Rewrite it again if you couldn't find the error. 
copy the sample again, and fill your actions.
also copy the file and paste it here, I might see the error. (enclose the file with ``` at the beginning and end)

**Comment by ReemAlsaffar** [comment]
This is the actions.json file 
```
{
    "manifest": {
        "displayName": "Blinky light",
        "invocationName": "Blinky light",
        "category": "PRODUCTIVITY"
    },
    "actions": [
        {
            "name": "com.example.actions.BlinkLight",
            "availability": {
                "deviceClasses": [
                    {
                        "assistantSdkDevice": {}
                    }
                ]
            },
            "intent": {
                "name": "com.example.intents.BlinkLight",
                "parameters": [
                    {
                        "name": "number",
                        "type": "SchemaOrg_Number"
                    },
                    {
                        "name": "speed",
                        "type": "Speed"
                    }
                ],
                "trigger": {
                    "queryPatterns": [
                        "blink ($Speed:speed)? $SchemaOrg_Number:number times",
                        "blink $SchemaOrg_Number:number times ($Speed:speed)?"
                    ]
                }
            },
            "fulfillment": {
                "staticFulfillment": {
                    "templatedResponse": {
                        "items": [
                            {
                                "simpleResponse": {
                                    "textToSpeech": "Blinking $number times"
                                }
                            },
                            {
                                "deviceExecution": {
                                    "command": "com.example.commands.BlinkLight",
                                    "params": {
                                        "speed": "$speed",
                                        "number": "$number"
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        },
         {
            "name": "vectory",
            "availability": {
                "deviceClasses": [
                    {
                        "assistantSdkDevice": {}
                    }
                ]
            },
            "intent": {
                "name": "vectory",
                "parameters": [],
                "trigger": {
                    "queryPatterns": [
                        "victory sign"
                    ]
                }
            },
            "fulfillment": {
                "staticFulfillment": {
                    "templatedResponse": {
                        "items": [
                            {
                                "simpleResponse": {
                                    "textToSpeech": "hooray! I'm victorious!"
                                }
                            },
                            {
                                "deviceExecution": {
                                    "command": "vectory",
                                    "params": {
                                    }
                                }
                            }
                        ]
                    }
                }
            }
        }, 
{
            "name": "Close Hand",
            "intent": {
                "name": "close hand",
                "parameters": [                ],
                "trigger": {
                    "queryPatterns": [
                        "close hand",
                        "Close fingers",
                        "close singers",
                        "hand close",
                        "han close",
                        "fingers close",
                        "hand Close",
                        "fingers Close",
                        "close fingers",
                        "Close hand",
                        "Close han",
                        "han Close",
                        "close",
                        "close han"
                    ]
                }
            },
            "fulfillment": {
                "staticFulfillment": {
                    "templatedResponse": {
                        "items": [
                            {
                                "simpleResponse": {
                                    "textToSpeech": "Closing Hand"
                                }
                            },
                            {
                                "deviceExecution": {
                                    "command": "Closing Hand",
                                     "params": {
                                        "number": "$number"
                                    }
                                    
                                }
                            }
                        ]
                    }
                }
            }
        },
        {
            "name": "MAIN",
            "intent": {
                "name": "actions.intent.MAIN",
                "parameters": [                ],
                "trigger": {
                    "queryPatterns": [
                    ]
                }
            },
            "fulfillment": {
                "staticFulfillment": {
                    "templatedResponse": {
                        "items": [
                            {
                                "simpleResponse": {
                                    "textToSpeech": "Control the arm"
                                }
                            }
                        ]
                    }
                }
            }
        }
    ],
    "types": [
        {
            "name": "$Speed",
            "entities": [
                {
                    "key": "SLOWLY",
                    "synonyms": [
                        "slowly",
                        "slow"
                    ]
                },
                {
                    "key": "NORMALLY",
                    "synonyms": [
                        "normally",
                        "regular"
                    ]
                },
                {
                    "key": "QUICKLY",
                    "synonyms": [
                        "quickly",
                        "fast",
                        "quick"
                    ]
                }
            ]
        }
    ]
}
```

**Comment by hasauino** [comment]
```
An Action Package cannot mix actions with device class availability restrictions, and actions without them
```
According to this message, the close hand action, does not define ``` "availability" ``` like other actions. try to add it to the close hand action.

**Comment by hasauino** [comment]
also the MAIN action

**Comment by ReemAlsaffar** [comment]
I added the availability and it worked

**Comment by ReemAlsaffar** [comment]
when I run the hotword.py I receive this error 
```
Traceback (most recent call last):
  File "hotword.py", line 33, in <module>
    from mylib import victoryFunction
  File "/home/pi/std_googleAssistant/scripts/mylib.py", line 7
    obj.write('l')
                 ^
IndentationError: unindent does not match any outer indentation level
``` 

This is the code in mylib:
```python
import serial
from time import sleep

def closeHand():
	obj=serial.Serial('/dev/ttyS0',9600)
    obj.write('l')
	
def victoryFunction():
   obj=serial.Serial('/dev/ttyS0',9600)
   obj.write('v')
```

and this is the hotword.py the event process code:
```python
def process_event(event):
    try:
        for a in event.actions:
            if(a[0]=='vectory'):
                victoryFunction()
            elif(a[0]=='Closing Hand'):
                closeHand()
    except:
        pass
```
when I edited just the victoryfunction it worked but when I added close hand this error showed up.

and I have a question, since I will be sending the characters how I can check myself if it working or not, or the only way to check is connecting it to the arduino?

**Comment by ReemAlsaffar** [comment]
and I added the import in hotword.py file 
```python 
from mylib import victoryFunction
from mylib import closeHand
```

**Comment by hasauino** [comment]
as the interpreter says,  indentations (spaces) are not consistent. 
it should be like:
```python
	obj=serial.Serial('/dev/ttyS0',9600)
        obj.write('l') .  # here the space was wrong 
```

**Comment by hasauino** [comment]
I'll make another issue for common errors like this. Let's keep this issue only for discussion. #3

**Comment by hasauino** [comment]
@ReemAlsaffar the code looks Ok, I think you got it now. But pay attention to this:
You cannot open serial communication more than once. That is, when the ```CloseHand``` function is called, it will open serial port ```ttyS0```. However, when you call it again or call function ```victoryFunction```, it will not open the port as it was already open. It will raise an error since the port is busy.

You have to put all behaviour functions inside a class. And the ```obj``` instance (an instance of the Serial class) can be defined as a class attribute inside the constructor. Then, you can call ```obj.write(..)``` in the other functions (behaviour functions) since they will be part of the class (class methods)

You may add a deconstructor method to close the serial port.

**Comment by hasauino** [comment]
Openning a serial port or closing or writing on it, is the same as you open, close, or write to a file

**Comment by ReemAlsaffar** [comment]
so I should make class for serial and in the functions for the behavior I just call the write ```obj.write('l')``` right?

**Comment by hasauino** [comment]
yes. You make a class, and in the constructor you define the serial object 
```python
# inside the consturctor
 self.obj=serial.Serial....
```

now you define the class methods, which are basically your behaviour functions:
```Python
 def myfunction(self):
    self.obj.write(....)
```

**Comment by hasauino** [comment]
this way, the serial port is opened once only. Then all the functions can use this port since the ```obj``` now is accessible to all of them.

**Comment by ReemAlsaffar** [comment]
```python
import serial
from time import sleep

def closeHand(self):
    obj.write('l')
    	
def victoryFunction(self):
   obj.write('v')
   
class serial:
  def __init__(self):
	self.obj=serial.Serial('/dev/ttyS0',9600)
```
and in the hotword.py I added ```from mylib import serial```

I identified class serial in mylib and added constructor but when I run it still I get error 
```
Traceback (most recent call last):
  File "hotword.py", line 33, in <module>
    from mylib import victoryFunction
  File "/home/pi/std_googleAssistant/scripts/mylib.py", line 13
    self.obj=serial.Serial('/dev/ttyS0',9600)
                                            ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by hasauino** [comment]
No exactly like that. Here how it should look like:
mylib:
```python

import serial

class behaviours:
    def __init__(self):
         self.obj=serial.Serial('/dev/ttyS0',9600)

    def closeHand(self):
         self.obj.write('l')
# and so on...
```

in ```hotword.py```, you just do:
```python
from mylib import behaviours
```
then you define a global variable of type ```behaviours``` (an instance of class behaviours) 

```python
# inside the main function
global object
object=behaviours()
```
then, in the event handler:
```python
# inside event handler function
def process_event(event):
    global object
    try:
        for a in event.actions:
            if(a[0]=='vectory'):
                object.victoryFunction()
            elif(a[0]=='Closing Hand'):
                object.closeHand()
    except:
        pass

```
if you find this confusing, review classes in Python. You may also read about python global variables how they are used.

**Comment by hasauino** [comment]
@ReemAlsaffar don't forget to push all your changes when you are done

**Comment by ReemAlsaffar** [comment]
I did as you said but still an error, and I tried to check the code over and over still I could not get what is wrong
```
Traceback (most recent call last):
  File "hotword.py", line 35, in <module>
    from mylib import behaviours
  File "/home/pi/std_googleAssistant/scripts/mylib.py", line 7
    self.obj = serial.Serial('/dev/ttyS0',9600)
                                              ^
TabError: inconsistent use of tabs and spaces in indentation
```
Here are the codes 
```python 
from mylib import behaviours

def process_event(event):
    global object 
    try:
        for a in event.actions:
            if(a[0]=='vectory'):
                object.victoryFunction()
            elif(a[0]=='Closing Hand'):
                object.closeHand()
    except:
        pass
```
and I added these in the beginning of  ```def main()```
```python
global object
object = behaviours()
```

This is mylib class:
```python
import serial

class behaviours:
  def __init__(self):
	self.obj = serial.Serial('/dev/ttyS0',9600)
  
  def closeHand(self):
    self.obj.write('l')
    	
  def victoryFunction(self):
    self.obj.write('v')
```

**Comment by hasauino** [comment]
``` TabError: inconsistent use of tabs and spaces in indentation ```. The error is in the spaces again.
a tap is different than the space, be careful. Some text editors replace the tap with 4 spaces, others with 8, ..etc.
the spaces have to be consistent...
you better avoid using <kbd>Tab</kbd> and only uses <kbd>Space</kbd>s. Some text editors give the option to write spaces when the <kbd>Tab</kbd> is pressed

**Comment by ReemAlsaffar** [comment]
I checked the spaces and I got this error:
```
Traceback (most recent call last):
  File "hotword.py", line 35, in <module>
    from mylib import behaviours
  File "/home/pi/std_googleAssistant/scripts/mylib.py", line 12
    def victoryFunction(self):
                             ^
IndentationError: unindent does not match any outer indentation level
```

**Comment by hasauino** [comment]
send me the file on email, or add it here on this repo.

**Comment by ReemAlsaffar** [comment]
I will push it here in the repository

**Comment by hasauino** [comment]
the problem is in line [12](https://github.com/UAEU-IRI/std_googleAssistant/blob/master/scripts/mylib.py#L12).

delete the spaces before ```def```, and do a tab instead.

Why?
line 12, there are 4 spaces
line 13, 1 tap 
It's as if  line 13 is one space. 

Use <kbd>space</kbd>s from now on. That's why I prefer {}.

**Comment by ReemAlsaffar** [comment]
The spaces problem is fixed, and I got another error but I fixed it with the exception, and now it is working, I will push the changes, and I will try to finish with the rest of the behavior table 
```
Traceback (most recent call last):
  File "/home/pi/env/lib/python3.5/site-packages/serial/serialposix.py", line 265, in open
    self.fd = os.open(self.portstr, os.O_RDWR | os.O_NOCTTY | os.O_NONBLOCK)
PermissionError: [Errno 13] Permission denied: '/dev/ttyS0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hotword.py", line 154, in <module>
    main()
  File "hotword.py", line 65, in main
    object = behaviours()
  File "/home/pi/std_googleAssistant/scripts/mylib.py", line 7, in __init__
    self.obj = serial.Serial('/dev/ttyS0',9600)
  File "/home/pi/env/lib/python3.5/site-packages/serial/serialutil.py", line 240, in __init__
    self.open()
  File "/home/pi/env/lib/python3.5/site-packages/serial/serialposix.py", line 268, in open
    raise SerialException(msg.errno, "could not open port {}: {}".format(self._port, msg))
serial.serialutil.SerialException: [Errno 13] could not open port /dev/ttyS0: [Errno 13] Permission denied: '/dev/ttyS0'
```

**Comment by hasauino** [comment]
of course you cannot just do that.
it says the port couldn't be opened, so non of the functions will work.
search this error. try to run the script with ```sudo```.
example: ``` sudo python hotword.py```

**Comment by ReemAlsaffar** [comment]
I did it and it showed this error:
```
Traceback (most recent call last):
  File "hotword.py", line 23, in <module>
    import pathlib2 as pathlib
ImportError: No module named pathlib2
```

**Comment by hasauino** [comment]
Ok, running it with ```sudo``` won't work.
If you run without ```sudo```, you won't have permission to open a serial port (for saftey, the user doesn't have this permission).

That's why the error was: ```[Errno 13] Permission denied: '/dev/ttyS0'```

search the internet for a solution, it must have happend to someone before.

**Comment by hasauino** [comment]
Check this [forum](https://askubuntu.com/questions/210177/serial-port-terminal-cannot-open-dev-ttys0-permission-denied). The first answer.

**Comment by ReemAlsaffar** [comment]
in place of {USER} I should put something else? or the same?

**Comment by ReemAlsaffar** [comment]
I checked it and the group mentioned is there:
```
pi : pi adm dialout cdrom sudo audio video plugdev games users input netdev spi i2c gpio
```
so I think not the problem in this

**Comment by ReemAlsaffar** [comment]
I solved the error 

https://www.raspberrypi.org/forums/viewtopic.php?t=223839
https://github.com/codebugtools/codebug_tether/issues/17 last comment 

I checked the above two links and it worked
