### ISSUE TITLE
ideas discussion

### ISSUE THREAD

**Issue by hasauino** [UAEU-IRI/std_googleAssistant#4]
Let's write suggestions here, and discuss them (what to approve what to reject)

**Comment by hasauino** [comment]
My first suggestion. Let's write the Rock paper scissor game today.

@amnaAlnaimi and @Hamda-alnuaimi : first write the logic on a separate draft paper. then try to implement it on Arduino. One round only, we don't need the score at this stage.

For testing, make your code listen to the Serial port 0 (the default serial port). So that you can send the character directly from the Serial monitor. (the Serial monitor can send as well, there is a text field and a send button). This way, you don't need the RPi, and it's much faster for testing.

At the end of the game round, you will send a character back to the RPi (send it on Serial 0). Reem will receive it and play a sound file according to the result (win or loose).

@ReemAlsaffar : Prepare sound files, for winning and loosing, and mage code changes so that you play a sound file upon receiving the character encoding the score result.

**Comment by amnaAlnaimi** [comment]
I like your idea, let’s do it like what you said.. one round and after that we will play sounds (for lose - won) . 
In this weekend, we will but more functions + put the strategy for the game .. 
*Sunday1–>we will start coding the game agin + fix the middle finger 
*Monday —> Finish remaining parts & I will start take photo and video for it.
*Tuesday—> I have to finish editing the video.

**Comment by hasauino** [comment]
@amnaAlnaimi , let's try to finish the video, recording+editing on Tuesday.

The rock paper scissor + memory game you and @Hamda-alnuaimi : Today, tomorrow, Saturday.

**Comment by hasauino** [comment]
@ReemAlsaffar, look at this web game: https://opentdb.com/api_config.php

this is a free data base of True/false questions.

For example. you can get a set of questions and their answers as a JSON message. For the Categroy you choose, and number of questions, type of questions..etc

Example: I choose the music category. 5 questions, true/false type. Here is the link:

https://opentdb.com/api.php?amount=5&category=12&difficulty=easy&type=boolean

When you do access this link (can be access from chrome, or from a python script!). You will get a response JSON message (viewed on the browser, or received in a Python script, there is a library for JSON message parsing in Python).

Here is the response you will receive:

```JSON

{
  "response_code": 0,
  "results": [
    {
      "category": "Entertainment: Music",
      "type": "boolean",
      "difficulty": "easy",
      "question": "The music group Daft Punk got their name from a negative review they recieved.",
      "correct_answer": "True",
      "incorrect_answers": [
        "False"
      ]
    },
    {
      "category": "Entertainment: Music",
      "type": "boolean",
      "difficulty": "easy",
      "question": "The alternative rock band, They Might Be Giants, released their album &#039;Flood&#039; in 1990. ",
      "correct_answer": "True",
      "incorrect_answers": [
        "False"
      ]
    },
    {
      "category": "Entertainment: Music",
      "type": "boolean",
      "difficulty": "easy",
      "question": "Daft Punk originated in France.",
      "correct_answer": "True",
      "incorrect_answers": [
        "False"
      ]
    },
    {
      "category": "Entertainment: Music",
      "type": "boolean",
      "difficulty": "easy",
      "question": "Scatman John&#039;s real name was John Paul Larkin.",
      "correct_answer": "True",
      "incorrect_answers": [
        "False"
      ]
    },
    {
      "category": "Entertainment: Music",
      "type": "boolean",
      "difficulty": "easy",
      "question": "Michael Jackson wrote The Simpsons song &quot;Do the Bartman&quot;.",
      "correct_answer": "False",
      "incorrect_answers": [
        "True"
      ]
    }
  ]
}


```

**Comment by amnaAlnaimi** [comment]
Sir .. is difficult for me actually Iast time I start editing at 2:00 pm and finished it at 8:30pm, but I will try

**Comment by ReemAlsaffar** [comment]
Ok I will check it today and try to work on it

**Comment by hasauino** [comment]
I will provide help, don't worry.

**Comment by hasauino** [comment]
check this out
https://youtu.be/vEfW8GVrHxM

**Comment by hasauino** [comment]
we don't need to make more games (we only need RPS (rock paper..), and memory sequence. we just have to find a way to move the arm as  google speaks, I'll think more into this, and you too guys
@ReemAlsaffar  @Hamda-alnuaimi @amnaAlnaimi

**Comment by ReemAlsaffar** [comment]
We will try to finish with Rock Paper Scissors game and the memory game, and for the game idea in the video I will try to see how it’s done and do it.

**Comment by amnaAlnaimi** [comment]
Sir, what you think if I work in (RPS) game and @Hamda-Alnuaimi work on (sequence) game ?

**Comment by amnaAlnaimi** [comment]
Sir I upload the strategy for the game .. please look at it to see if it good or not

**Comment by ReemAlsaffar** [comment]
sir in google assistant can we change ok google to ok fellow or any other name we want?

**Comment by hasauino** [comment]
> We will try to finish with Rock Paper Scissors game and the memory game, and for the game idea in the video I will try to see how it’s done and do it.

@ReemAlsaffar , These are already built in. When I run my google project they are already there, you should also be able to say them.



> Sir, what you think if I work in (RPS) game and @Hamda-alnuaimi work on (sequence) game ?

Yes, but all of you help each other so you finish all in time.



> Sir I upload the strategy for the game .. please look at it to see if it good or not

@amnaAlnaimi Ok will have a look at it, thank you.



> sir in google assistant can we change ok google to ok fellow or any other name we want?

@ReemAlsaffar No, google assistant library does not support custom hotword. There are work arounds, but I don't think it's worth the time that will be spent.

**Comment by ReemAlsaffar** [comment]
so should I try to test it on raspberry on Sunday? I mean the game idea

**Comment by hasauino** [comment]
@ReemAlsaffar  Do you have the RPi with you? 
Run your google assistant, and see if accepts those commands (built-in games, story telling). Most probably it will be include (because mine is the same as yours).

No, your part is to find a way to control the arm as google speaks. Make gestures, or make it look interactive and alive.

**Comment by amnaAlnaimi** [comment]
Sir. Now I finished the game , I think it will work now. When you free. Look at my logic. I put commands in each step.

**Comment by ReemAlsaffar** [comment]
No I do not have it with me, I will try to find a way

**Comment by hasauino** [comment]
@amnaAlnaimi Great! I will see it now. Did you test it?

@ReemAlsaffar You will have to install it on your computer, and do testing there. I will make a clone SD card so you can take another RPi to home

**Comment by amnaAlnaimi** [comment]
Sir. I don’t upload it yet just give me 5 min because I want to read the code again. No sir I don’t have the arm with me . Sunday morning I will test it. Inshaallah

**Comment by hasauino** [comment]
Ok, from now on, @Hamda-alnuaimi and @amnaAlnaimi keep the arm with you.
@ReemAlsaffar I will give you another RPi which is same exact as yours with a mic for testing at home

**Comment by Hamda-alnuaimi** [comment]
Ok

Sent from my iPhone

On Jan 17, 2019, at 8:42 PM, Hassan Umari <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok, from now on, @Hamda-alnuaimi<https://github.com/Hamda-alnuaimi> and @amnaAlnaimi<https://github.com/amnaAlnaimi> keep the arm with you.
@ReemAlsaffar<https://github.com/ReemAlsaffar> I will give you another RPi which is same exact as yours with a mic for testing at home

**Comment by ReemAlsaffar** [comment]
> @amnaAlnaimi Great! I will see it now. Did you test it?
> 
> @ReemAlsaffar You will have to install it on your computer, and do testing there. I will make a clone SD card so you can take another RPi to home


how to install it on my laptop?

**Comment by hasauino** [comment]
@amnaAlnaimi The logic is OK. I will check your code and match it with the logic you wrote once you upload it.

@ReemAlsaffar ah, you need Ubuntu to do it. Ok then, you cannot test it at home.

**Comment by amnaAlnaimi** [comment]
Sir it available now

**Comment by hasauino** [comment]
Ok thanks. By mistake you didn't put them in the "Arduino" directory...

**Comment by amnaAlnaimi** [comment]
Yes sorry I will upload it again

**Comment by ReemAlsaffar** [comment]
> @amnaAlnaimi The logic is OK. I will check your code and match it with the logic you wrote once you upload it.
> 
> @ReemAlsaffar ah, you need Ubuntu to do it. Ok then, you cannot test it at home.

ok sir, then I will try to finish editing hotword.py, and actions.json, and I will try after that to find a way to control the arm when google speaks

**Comment by hasauino** [comment]
@amnaAlnaimi Great work, I think it will work just fine. But there are few minor comments I added. Did you see them?

**Comment by hasauino** [comment]
@ReemAlsaffar if possible, can you check how to make an action that continues the conversation. I will look into it too..

**Comment by hasauino** [comment]
@Hamda-alnuaimi I will review your game and logic when you add them first just add the logic, a picture of a draft paper..).

**Comment by ReemAlsaffar** [comment]
> @ReemAlsaffar if possible, can you check how to make an action that continues the conversation. I will look into it too..

ok I will search about it

**Comment by Hamda-alnuaimi** [comment]
Ok

Sent from my iPhone

On Jan 17, 2019, at 9:35 PM, Hassan Umari <notifications@github.com<mailto:notifications@github.com>> wrote:


@Hamda-alnuaimi<https://github.com/Hamda-alnuaimi> I will review your game and logic when you add them first just add the logic, a picture of a draft paper..).

**Comment by amnaAlnaimi** [comment]
@hasauino thanks, you add it in the code?

**Comment by Hamda-alnuaimi** [comment]
I hope it’s clear 




Sent from my iPhone

**Comment by hasauino** [comment]
@Hamda-alnuaimi can you send it again, or upload it here. I lost it

**Comment by Hamda-alnuaimi** [comment]
ook

**Comment by hasauino** [comment]
@Hamda-alnuaimi 
Thank you Hamda. Arm should do a sequence AFTER the start is pressed. I think it will be confusing your way. 
Hamda, I will look at your code directly when you implement. It should be done today right?
Also, you are not telling @ReemAlsaffar  what the google assistant should say?

For example, before the start button is ON, the goolge assistant should be introducing the game and how to play instructions. 
maybe also, when the user presses start, you send a character to RPi, so it can play a sound effect of entering the game.

Also when the user wins, the arm should do something.. (victory sign.. or anything you believe will look fun ...etc)  

also a loose animation too.

@ReemAlsaffar  @amnaAlnaimi what is the progress

**Comment by ReemAlsaffar** [comment]
I added more things to actions.json, only the python code is left but the RPS game steps and some other actions steps I have already wrote them so I think I can do it at night today. And after Hamda finish the implementation of the game I will add the things for it.

________________________________

**Comment by Hamda-alnuaimi** [comment]
There’s a win or lose at the end, like what you said we’ll send a char for Reem but at the beginning when we say let’s play the sequence game I think it should be the same as RBR?  explain the instructions and then start..

Sent from my iPhone

On Jan 19, 2019, at 3:48 PM, Hassan Umari <notifications@github.com<mailto:notifications@github.com>> wrote:


@Hamda-alnuaimi<https://github.com/Hamda-alnuaimi>
Thank you Hamda. Arm should do a sequence AFTER the start is pressed. I think it will be confusing your way.
Hamda, I will look at your code directly when you implement. It should be done today right?
Also, you are not telling @ReemAlsaffar<https://github.com/ReemAlsaffar> what the google assistant should say?

For example, before the start button is ON, the goolge assistant should be introducing the game and how to play instructions.
maybe also, when the user presses start, you send a character to RPi, so it can play a sound effect of entering the game.

Also when the user wins, the arm should do something.. (victory sign.. or anything you believe will look fun ...etc)

also a loose animation too.

@ReemAlsaffar<https://github.com/ReemAlsaffar> @amnaAlnaimi<https://github.com/amnaAlnaimi> what is the progress

**Comment by hasauino** [comment]
@ReemAlsaffar did you find anything regarding making an action that continues the conversation? 

@Hamda-alnuaimi Ok. It's your design and your choice. But please, try to make it really good, clear, easy from the user perspective.

All of you, please upload any file you change so I can see and the rest of the team

**Comment by ReemAlsaffar** [comment]
No still, yeah I will upload the files tonight.

________________________________
